import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { GlobalNav } from '@/ui/global-nav'
import { ThemeChanger } from '@/ui/theme-changer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <main className="h-screen bg-white dark:bg-zinc-900 dark:text-akairosu-white flex">
            <GlobalNav />
            <div className="flex flex-col">
              <div className="invisible lg:visible w-screen h-10 dark:h-8 border-b-4 bg-zinc-200 dark:bg-akairosu-white border-zinc-300 dark:border-akairosu-orange"></div>
              <div className="lg:pl-80 w-full h-full flex">
                <div className="mx-auto px-2 pt-20 lg:p-0 flex">
                  {/* had to add lg:left-auto to make it work both sides */}
                  <ThemeChanger className="fixed lg:top-14 lg:right-6 lg:left-auto left-3 top-3 z-10" />
                  {children}
                </div>
              </div>
              <div className="bottom-0 invisible lg:visible w-screen h-10 dark:h-8 bg-zinc-200 dark:bg-akairosu-white border-t-4 border-zinc-300 dark:border-akairosu-orange"></div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
