import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { GlobalNav } from '@/ui/global-nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <main className="bg-white dark:bg-zinc-900 dark:text-akairosu-white flex h-screen">
            <GlobalNav />
            <div className="lg:pl-80 w-full h-full flex">
              <div className="mx-auto px-2 pt-20 lg:p-8 flex">
                {children}
              </div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
